import type { SearchPageItem } from "@/data/search/searchAllContent";
import type { DownloadFilterOption } from "@/data/support/downloadCenterContent";

/** Figma 6430:112540 — Search Pages tab + filter */
export const searchPagesPage = {
  totalResults: 2658,
  pageSize: 10,
} as const;

export const searchPageTypes: DownloadFilterOption[] = [
  { id: "markets", label: "Markets", count: 100 },
  { id: "service", label: "Service", count: 100 },
  { id: "support", label: "Support", count: 100 },
  { id: "company", label: "Company", count: 352 },
];

/** Figma 6430:112540 — page 1 list (10 items) */
const pagesPool: SearchPageItem[] = [
  {
    id: "spg-1",
    href: "/markets/data-center",
    category: "Markets",
    title: "Power your data center with reliable electrical solutions",
    mark: "DC Device",
    highlight: "DC Device",
    description:
      "On the 18th, LS ELECTRIC announced that its switchgear manufacturing subsidiary, “MCM Engineering II,” located in Iron County, Utah, has been approved for a tax-reduction incentive by the Utah Inland Port Authority (UIPA), an economic agency under the Utah state government. The key point of this incentive is a reduction of up to 30% of the increase in property taxes generated by the...",
  },
  {
    id: "spg-2",
    href: "/company/events/detail",
    category: "Company",
    title: "Int’l Smart Grid Expo (SG Expo)",
    mark: "DC Device",
    highlight: "DC Device",
    description:
      "LS Energy Solutions : LS Energy Solutions delivers advanced DC Device Energy Storage Systems (ESS) and grid optimization technologies. By integrating power electronics, control systems, and project expertise, the company supports renewable integration and  grid stability across global markets.",
  },
  {
    id: "spg-3",
    href: "/support/connect-portal",
    category: "Service",
    title: "Explore our service coverage and support options",
    mark: "DC Device",
    highlight: "DC Device",
    description:
      "On the 18th, LS ELECTRIC announced that its switchgear manufacturing subsidiary, “MCM Engineering II,” located in Iron County, Utah, has been approved for a tax-reduction incentive by the Utah Inland Port Authority (UIPA), an economic agency under the Utah state government. The key point of this DC Device incentive is a reduction of up to 30% of the increase in property taxes...",
  },
  {
    id: "spg-4",
    href: "/support/where-to-buy",
    category: "Service",
    title: "Find authorized partners for local technical support",
    mark: "DC Device",
    highlight: "DC Device",
    description:
      "LS Energy Solutions : LS Energy Solutions delivers advanced Energy Storage Systems (ESS) and grid optimization technologies. By integrating power electronics, control systems, and project expertise, the company supports renewable integration and  grid stability across global markets.",
  },
  {
    id: "spg-5",
    href: "/markets/data-center",
    category: "Markets",
    title: "Power your data center with reliable electrical solutions",
    mark: "DC Device",
    highlight: "DC Device",
    description:
      "On the 18th, LS ELECTRIC announced that its switchgear manufacturing subsidiary, “MCM Engineering II,” located in Iron County, Utah, has been approved for a tax-reduction incentive by the Utah Inland Port Authority (UIPA), an economic agency under the Utah state government. The key point of this incentive is a reduction of up to 30% of the increase in property taxes generated by the...",
  },
  {
    id: "spg-6",
    href: "/support/connect-portal",
    category: "Service",
    title: "Explore our service coverage and support options",
    mark: "DC Device",
    highlight: "DC Device",
    description:
      "On the 18th, LS ELECTRIC announced that its switchgear manufacturing subsidiary, “MCM Engineering II,” located in Iron County, Utah, has been approved for a tax-reduction DC Device incentive by the Utah Inland Port Authority (UIPA), an economic agency under the Utah state government. The key point of this incentive is a reduction of up to 30% of the increase in property taxes...",
  },
  {
    id: "spg-7",
    href: "/company/events/detail",
    category: "Company",
    title: "Int’l Smart Grid Expo (SG Expo)",
    mark: "DC Device",
    highlight: "DC Device",
    description:
      "LS Energy Solutions : LS Energy Solutions delivers advanced Energy Storage Systems (ESS) and grid optimization technologies. By integrating power electronics, control systems, and project expertise, the company supports renewable integration and  grid stability across global markets DC Device.",
  },
  {
    id: "spg-8",
    href: "/support/where-to-buy",
    category: "Service",
    title: "Find authorized partners for local technical support",
    mark: "DC Device",
    highlight: "DC Device",
    description:
      "On the 18th, LS ELECTRIC announced that its switchgear manufacturing subsidiary, “MCM Engineering II,” located in Iron County, Utah, has been approved for a tax-reduction DC Device incentive by the Utah Inland Port Authority (UIPA), an economic agency under the Utah state government. The key point of this incentive is a reduction of up to 30% of the increase in property taxes...",
  },
  {
    id: "spg-9",
    href: "/company/events/detail",
    category: "Company",
    title: "Int’l Smart Grid Expo (SG Expo)",
    mark: "DC Device",
    highlight: "DC Device",
    description:
      "LS Energy Solutions : LS Energy Solutions delivers advanced Energy Storage Systems (ESS) and grid optimization technologies. By integrating power electronics, control systems, and project expertise, the company supports renewable integration and  grid stability across global markets DC Device.",
  },
  {
    id: "spg-10",
    href: "/support/where-to-buy",
    category: "Service",
    title: "Find authorized partners for local technical support",
    mark: "DC Device",
    highlight: "DC Device",
    description:
      "On the 18th, LS ELECTRIC announced that its switchgear manufacturing subsidiary, “MCM Engineering II,” located in Iron County, Utah, has been approved for a tax-reduction DC Device incentive by the Utah Inland Port Authority (UIPA), an economic agency under the Utah state government. The key point of this incentive is a reduction of up to 30% of the increase in property taxes...",
  },
];

export function getSearchPagesPageItems(page: number, pageSize: number): SearchPageItem[] {
  const start = (page - 1) * pageSize;
  const items: SearchPageItem[] = [];

  for (let i = 0; i < pageSize; i++) {
    const globalIndex = start + i;
    const source = pagesPool[globalIndex % pagesPool.length];
    items.push({
      ...source,
      id: `${source.id}-p${page}-${i}`,
    });
  }

  return items;
}
