export const pressDetailHero = {
  src: "/img/company/press/detail_hero.png",
  alt: "LS ELECTRIC exhibition at Energy Highway business showcase",
};

/** Figma 3525:39831 — devices_product_video__player 패턴 */
export const pressDetailYoutube = {
  videoId: "WtQN9rcdI-0",
  title: "LS ELECTRIC MCCB Line Introduction (ENG)",
  poster: "/img/company/press/detail_video_poster.png",
};

export const pressDetailBullets = [
  "Utah Inland Port Authority decides on tax relief for the MCM Engineering II expansion project",
  "To invest $168 million by 2030 to build three new production buildings",
  "Accelerating localization strategy by establishing new business bases in Dallas and Atlanta, U.S.",
];

export const pressDetailParagraphs = [
  "LS ELECTRIC is gaining momentum in its effort to expand its North American business, as its production base expansion project underway in Utah, USA, will receive incentive support from a local public agency.",
  "On the 18th, LS ELECTRIC announced that its switchgear manufacturing subsidiary, \u201cMCM Engineering II,\u201d located in Iron County, Utah, has been approved for a tax-reduction incentive by the Utah Inland Port Authority (UIPA), an economic agency under the Utah state government. The key point of this incentive is a reduction of up to 30% of the increase in property taxes generated by the business expansion over the next 25 years.",
  "LS ELECTRIC plans to invest a total of $168 million (about KRW 250 billion) to triple MCM Engineering II's switchgear production capacity. It will expand the plant from its current 13,223㎡ (about 4,000 pyeong) to 79,338㎡ (about 24,000 pyeong)—a sixfold increase—and will additionally construct three production buildings by 2030.",
  "MCM Engineering II is a local switchgear manufacturer that LS ELECTRIC acquired in 2022 with an investment of $6.3 million (about KRW 7.7 billion).",
  "LS ELECTRIC plans to use Utah's MCM Engineering II and its Bastrop, Texas campus as its two key production bases to fully expand its North American business. By 2030, it will invest a total of $240 million (about KRW 350 billion) across production bases throughout North America, with a strategy to complete a localized value chain encompassing local sales, design, production, and service.",
  "Meanwhile, LS ELECTRIC also plans to establish new business bases in \u201cDallas, Texas,\u201d and \u201cAtlanta, Georgia,\u201d which are strategic regions in the U.S. Within the first quarter of this year, it plans to set up a local sales and service office in Dallas, Texas, and within the year add another business base in Atlanta, Georgia\u2014pursuing thorough localization and providing differentiated customer service.",
  "LS ELECTRIC is expected to further accelerate its localization strategy by securing offices in strategic regions in addition to major business hubs such as its Chicago corporation and its LA western branch.",
  "An LS ELECTRIC official said, \u201cWith excellent talent, infrastructure, and a business-friendly regulatory environment, Utah is a highly competitive region for LS ELECTRIC to continuously expand its advanced switchgear manufacturing capabilities,\u201d adding, \u201cThrough this campus expansion project, we will further strengthen our responsiveness to the North American market and accelerate growth in our global power infrastructure business.\u201d",
];

export const pressDetailPager = {
  prev: {
    href: "/company/articles/detail",
    title: "LS ELECTRIC to shake up the industry in the era of a Supercycle",
  },
  next: {
    href: "/company/press/detail",
    title:
      "LS ELECTRIC Unveils a Wide Range of Future-Oriented Manufacturing AX Solutions",
  },
};
